### ISSUE TITLE
Allow for custom colours in spell instructions

### ISSUE THREAD

**Issue by CocytusDEDI** [CocytusDEDI/MMSpellbook#12]
A new section could be used to specify metadata like `config:` or `about:` and the option to specify colour could be in there.

**Comment by AndycptSher** [comment]
## request for clarification

could the syntax for how metadata should be specified be given? (preferably with examples)

**Comment by CocytusDEDI** [comment]
# Specification
I hadn't thought about it until now, but I think a good way to do it is by equating it. The format being a variable on the left-hand side and have a value on the right. Values can be:
- Strings: in the form `"my string"`
- Numbers: they should all be interpreted as f64s
- Lists: in the form `[my_item, another_item]`
  - The Items in lists can be any other data type
  - Spacing doens't matter
- Booleans: true or false (capitalisation doesn't matter)
- Dictionaries: in the form {key, value}
  - The keys can only be strings and numbers, while values can be any other data type

Spacing doesn't matter, and possible start of a new variable should be donated by a new line. I say possible as it doesn't matter if there are multiple new lines between variables.

Specifically for colours, it should be a list of three numbers representing red, green and blue in that order. The numbers can range from 0 to 1. The color variable can be either the American English or British English spelling, the priority to implement is the American English one. Since only color is planned right now, the only values that need implementing currently are Lists and Numbers.

I have also decided on `about` as the section name.

## Realistic example

```
about:
color = [0.4, 0, 0.8]
```

## Limit testing example
```
  about    : 
     color      =        [   0.212,    1,2.3]
```

## Multiple (non planned) variables
```
about:
color = [1, 1, 1]
something_else = {"something": 4, "something_else": 6.3}
more = true
```
