### ISSUE TITLE
Tests for spell processing

### ISSUE THREAD

**Issue by AndycptSher** [CocytusDEDI/MMSpellbook#20]
add tests in lib.rs for spell processing/component executing functions

**Comment by CocytusDEDI** [comment]
I'll have to review how much of that is possible, as some of it relies on Godot and tests can't be written for anything that uses Godot features.

**Comment by CocytusDEDI** [comment]
I don't believe this can be done without large refactors, plus even if it could be done it wouldn't be very meaningful as most likely only small parts of `lib.rs` would be able to be tested.
