### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by AndycptSher** [CocytusDEDI/MMSpellbook#32]
## Note: possible bug
current implementation permits if statements in about section introducing possible parsing errors as additional opcodes have not been accounted for

_Originally posted by @AndycptSher in https://github.com/CocytusDEDI/MMSpellbook/issues/30#issuecomment-2282792187_

**Comment by CocytusDEDI** [comment]
The about section code hasn't been merged yet, and so shouldn't be listed as an issue on this repository.
